#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GaoHongchen's Blog
email: cggos@outlook.com
bio: 'Stay hungry,Stay foolish'
description: "SLAM | Computer Vision | HPC"
locale: utf-8

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: cggosc
github_username:  cggos
social_media:
  github_url: https://github.com/cggos
  weibo_url: http://weibo.com/gaohongchen01
  zhihu_url: https://www.zhihu.com/people/gaohongchen01
  twitter_url: https://twitter.com/cggosc
  lofter_url: http://gaohongchen01.lofter.com/

markdown: kramdown

mathjax: true

# theme: minima #jekyll-theme-slate

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/pages:num/"

excerpt_separator: <!-- more -->

permalink: /:categories/:title.html

author: GaoHongchen

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
